<div id="section_accueil">
    <div id="carousel-container">
        <div class="carousel">
            <img src="public/images/daniel-mingook-kim-UXR--t8CZ1U-unsplash.jpg" alt="méditation">
            <img src="public/images/igor-miske-CwVE4xCAA8Y-unsplash.jpg" alt="thé">
            <img src="public/images/katherine-hanlon-QgcdtM9rA5s-unsplash.jpg" alt="acupuncture">
            <img src="public/images/oriento-bAzDhilQFsA-unsplash.jpg" alt="livre classique">
        </div>
    </div>
</div>

    <div class="box" id="box_accueil">
    <section>
    <h1> Equilibrez votre santé grâce à la Médecine Chinoise</h1>
    
        <p>La Chine, un nom qui résonne d'éternité. Considérée comme la plus ancienne civilisation continue de l'humanité, elle a façonné tout au long de son histoire un art médical séculaire d'une beauté inégalée. Depuis quelques décennies, elle a ouvert grand ses portes, laissant échapper la douceur de sa sagesse exotique, qui voyage à travers le monde pour venir toucher les cœurs.
    
    L'intérêt pour la médecine chinoise a ainsi fleuri, avec l'apparition d'écoles d'acupuncture et de laboratoires de plantes médicinales chinoises dans tous les coins du globe. Mais pourquoi tant de patients se tournent-ils vers cette forme de médecine alternative ou complémentaire ? Est-ce simplement pour son efficacité ? Pas seulement.
    
    En vérité, même si la science et la biomédecine ne cessent de progresser, elles ne suffisent plus à combler les besoins des patients. Ce sont eux qui montrent le chemin, ils veulent avant tout être écoutés, compris, connectés à leur thérapeute. Et l'humanité a toujours eu besoin de rester en lien avec la nature. Depuis des temps immémoriaux, les penseurs chinois, et particulièrement les médecins, ont cherché à vivre en harmonie avec elle.
    
    C'est cela que la médecine chinoise a à offrir : une bienveillance qui réchauffe l'âme, une harmonie qui apaise l'esprit, et une efficacité qui soulage le corps. Ainsi, la sagesse millénaire de la Chine s'infiltre dans l'histoire pour venir toucher le monde entier de sa douceur et de sa grâce. Pas étonnant que la médecine chinoise soit de plus en plus prisée, car elle résonne avec la poésie de la vie elle-même.</p>
    </section>
    </div>

