<div class="box" id="box_article">
    <form method="POST">
        <span>Titre :</span><input type="text" name="titre" placeholder="Tapez ici votre titre" />
        <span>Image :</span><input type="text"name="image" placeholder="Image en Url"/>
        <span>Contenu :</span><input type="text" name="contenu" placeholder="Tapez ici votre commentaire" />
        <span>Date : </span><input type="datetime-local" name="date_publication"/>
        <input type="submit" name="poster" />
    </form>
</div>