<div class="box" id="box_inscription">
    <form method="POST">
        <span>Nom</span><input type="text" name="nom" placeholder="NOM" />
        <span>Prénom</span><input type="text" name="prenom" placeholder="prenom" />
        <span>Téléphone</span><input type="text" name="telephone" placeholder="téléphone" />
        <span>Date de naissance</span><input type="text" name="date_naissance" placeholder="date de naissance" />
        <span>Adresse</span><input type="text" name="adresse" placeholder="adresse" />
        <span>Email</span><input type="email" name="email" placeholder="example@example.com" />
        <span>Répétez email </span><input type="email" name="email2" placeholder="Veuillez saisir votre email à nouveau" />
        <span>Mot de passe</span><input type="password" name="password" placeholder="Veuillez saisir votre mot de passe" />
        <span>Répétez Mot de passe</span><input type="password" name="password2" placeholder="Veuillez saisir votre mot de passe à nouveau" />
        <input type="submit" name="subscribe" />
    </form>
</div>