<div class="box" id="box_prestation">
<form method="POST">
    <span>Nom</span> <input type="text" name="nom_prestation" placeholder="nom_prestation" />
    <span> Description :</span> <input type="text" name="definition" placeholder="definition" />
    <span>Durée : </span><input type="text" name="duree" placeholder="duree" />
    <span>Cout :</span><input type="text" name="cout" placeholder="cout" />
    <input type="submit" name="poster" />
</form>